import { NextRequest, NextResponse } from "next/server";
import { requireOrgAdminFromToken, logAuditEvent } from "@/lib/server/organization-auth";
import { createSupabaseAdminClient } from "@/lib/supabase-server";

// GET /api/org/reports/export - Export training hours as CSV
export async function GET(request: NextRequest) {
  try {
    const token = request.headers.get("x-org-token") ?? undefined;
    const adminWithOrg = await requireOrgAdminFromToken(token);

    const { searchParams } = new URL(request.url);
    const format = searchParams.get("format") || "csv";

    // Default to current month
    const now = new Date();
    const defaultStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split("T")[0];
    const defaultEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().split("T")[0];

    const startDate = searchParams.get("startDate") || defaultStart;
    const endDate = searchParams.get("endDate") || defaultEnd;

    const supabase = createSupabaseAdminClient();

    // Get all sessions with full details
    const { data: sessions } = await supabase
      .from("training_sessions")
      .select(`
        id,
        session_date,
        start_time,
        end_time,
        duration_minutes,
        session_type,
        topics_covered,
        status,
        approved_by_teacher,
        approved_by_org,
        billable,
        billed,
        student_id,
        teacher_id,
        students!student_id (name, email),
        portal_users!teacher_id (name, email)
      `)
      .eq("organization_id", adminWithOrg.organizationId)
      .gte("session_date", startDate)
      .lte("session_date", endDate)
      .order("session_date", { ascending: true });

    // Get employee info
    const { data: employees } = await supabase
      .from("organization_employees")
      .select("student_id, employee_id, department, job_title")
      .eq("organization_id", adminWithOrg.organizationId);

    const employeeMap = new Map((employees || []).map((e: any) => [e.student_id, e]));

    // Build CSV
    const headers = [
      "Date",
      "Start Time",
      "End Time",
      "Duration (Minutes)",
      "Duration (Hours)",
      "Session Type",
      "Student Name",
      "Student Email",
      "Employee ID",
      "Department",
      "Job Title",
      "Teacher Name",
      "Topics Covered",
      "Status",
      "Teacher Approved",
      "Org Approved",
      "Billable",
      "Billed",
    ];

    const rows = (sessions || []).map((s: any) => {
      const emp = employeeMap.get(s.student_id) as any;
      return [
        s.session_date,
        s.start_time || "",
        s.end_time || "",
        s.duration_minutes,
        (s.duration_minutes / 60).toFixed(2),
        s.session_type,
        s.students?.name || "",
        s.students?.email || "",
        emp?.employee_id || "",
        emp?.department || "",
        emp?.job_title || "",
        s.portal_users?.name || "",
        (s.topics_covered || "").replace(/"/g, '""'),
        s.status,
        s.approved_by_teacher ? "Yes" : "No",
        s.approved_by_org === true ? "Yes" : s.approved_by_org === false ? "No" : "Pending",
        s.billable ? "Yes" : "No",
        s.billed ? "Yes" : "No",
      ];
    });

    // Calculate totals
    const totalMinutes = (sessions || []).reduce((sum: number, s: any) => sum + s.duration_minutes, 0);
    const billableMinutes = (sessions || [])
      .filter((s: any) => s.billable && s.status === "completed")
      .reduce((sum: number, s: any) => sum + s.duration_minutes, 0);

    // Add summary row
    rows.push([]);
    rows.push(["SUMMARY"]);
    rows.push(["Total Sessions", (sessions || []).length.toString()]);
    rows.push(["Total Hours", (totalMinutes / 60).toFixed(2)]);
    rows.push(["Billable Hours", (billableMinutes / 60).toFixed(2)]);
    rows.push(["Period", `${startDate} to ${endDate}`]);
    rows.push(["Organization", adminWithOrg.organization.name]);
    rows.push(["Generated", new Date().toISOString()]);
    rows.push(["Generated By", adminWithOrg.name]);

    // Build CSV string
    const csvContent = [
      headers.map((h) => `"${h}"`).join(","),
      ...rows.map((row) =>
        row.map((cell) => (typeof cell === "string" && cell.includes(",") ? `"${cell}"` : cell)).join(",")
      ),
    ].join("\n");

    // Audit log
    await logAuditEvent({
      organizationId: adminWithOrg.organizationId,
      actorType: "org_admin",
      actorId: adminWithOrg.id,
      actorName: adminWithOrg.name,
      action: "report_exported",
      details: {
        format,
        startDate,
        endDate,
        sessionCount: (sessions || []).length,
        totalHours: (totalMinutes / 60).toFixed(2),
      },
    });

    const filename = `training-hours-${adminWithOrg.organization.slug}-${startDate}-to-${endDate}.csv`;

    return new NextResponse(csvContent, {
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`,
      },
    });
  } catch (err) {
    const status = typeof (err as any).statusCode === "number" ? (err as any).statusCode : 500;
    return NextResponse.json(
      { message: err instanceof Error ? err.message : "Failed to export report." },
      { status }
    );
  }
}
